name: Build and Push Contoso-App

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Wichtig: erlaubt Push zu ghcr.io

    steps:
      - uses: actions/checkout@v4

      - name: Set Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/quovadis1212/contoso-app:${{ github.sha }}
            ghcr.io/quovadis1212/contoso-app:latest

      - name: Smoke Test
        run: npm test
