name: Build, Test and Push Contoso-App

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    # GitHub-Token braucht Schreibrechte für GHCR
    permissions:
      contents: read
      packages: write

    steps:
      # --- 1. Checkout ---
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- 2. Commit-Hash setzen (für Versionierung) ---
      - name: Set Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # --- 3. Login zu GitHub Container Registry (GHCR) ---
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 4. Docker-Image bauen und pushen ---
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/quovadis1212/contoso-app:${{ github.sha }}
            ghcr.io/quovadis1212/contoso-app:latest

      # --- 5. Smoke-Test (lokaler Node-Test) ---
      - name: Smoke Test
        run: |
          npm start &
          for i in {1..10}; do
            nc -z localhost 3000 && break
            echo "⏳ Waiting for app to start..."
            sleep 1
          done
          npm test

      # --- 6. E2E-Test gegen Container ---
      - name: Run container for e2e test
        run: |
          docker run -d -p 3000:3000 ghcr.io/quovadis1212/contoso-app:${{ github.sha }}
          for i in {1..10}; do
            nc -z localhost 3000 && break
            echo "⏳ Waiting for container..."
            sleep 1
          done
          curl -f http://localhost:3000/healthz

      # --- 7. Automatisches Update im GitOps-Repo (Image-Tag) ---
      - name: Update image tag in GitOps repo
        run: |
          git clone https://github.com/Quovadis1212/gitops-config.git
          cd gitops-config/environments/dev
          yq -i '.image.tag = "${{ github.sha }}"' values.yaml
          git config user.name "CI Bot"
          git config user.email "ci@contoso.local"
          git commit -am "Update Contoso-App image tag to ${{ github.sha }}"
          git push
